# Generated by Django 6.0.3 on 2026-05-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
