# Generated by Django 6.0.3 on 2026-04-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alokasimateria',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.professor'),
        ),
        migrations.AddField(
            model_name='alokasimateria',
            name='disiplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disiplina'),
        ),
        migrations.AddField(
            model_name='alokasimateria',
            name='klase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.klase'),
        ),
        migrations.AlterUniqueTogether(
            name='alokasimateria',
            unique_together={('disiplina', 'klase')},
        ),
    ]
