# Generated by Django 6.0.3 on 2026-04-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('id_funcionario', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('naran_kompletu', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Permanente', 'Permanente'), ('Kontratadu', 'Kontratadu'), ('Voluntariu', 'Voluntariu')], default='Permanente', max_length=15)),
                ('nu_telemovel', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_emis', models.CharField(max_length=20, unique=True)),
                ('naran_kompletu', models.CharField(max_length=255)),
                ('sexu', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudante_fotos/')),
                ('status', models.CharField(default='Ativu', max_length=10)),
                ('klase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.klase')),
            ],
        ),
    ]
