# Generated by Django 6.0.3 on 2026-05-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cargo',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Diretor/a da Escola', 'Diretor/a da Escola')], default='Professor', max_length=25, null=True),
        ),
    ]
