# Generated by Django 6.0.3 on 2026-05-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlokasiMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disiplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran_disiplina', models.CharField(max_length=100, unique=True)),
                ('kodigu', models.CharField(max_length=10, unique=True)),
                ('departamentu', models.CharField(choices=[('CN', 'IPA (CN)'), ('CSH', 'IPS (CSH)'), ('Geral', 'Geral')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Klase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('departamentu', models.CharField(choices=[('CN', 'Ciencias Naturais'), ('CSH', 'Ciencias Sociais e Humanidades')], max_length=3)),
                ('turma', models.CharField(max_length=5)),
            ],
        ),
    ]
