# Generated by Django 6.0.3 on 2026-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisaunVizaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=100)),
                ('deskrisaun', models.TextField()),
            ],
        ),
    ]
