# Generated by Django 6.0.3 on 2026-06-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_misaunvizaun'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstoriaEskola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskrisaun', models.TextField(verbose_name='Deskrisaun Istória Badak')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Istória Eskola',
            },
        ),
    ]
