# Generated by Django 6.0.3 on 2026-06-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_istoriaeskola'),
    ]

    operations = [
        migrations.AddField(
            model_name='istoriaeskola',
            name='organograma',
            field=models.ImageField(blank=True, null=True, upload_to='organograma/'),
        ),
    ]
