# Generated by Django 6.0.3 on 2026-05-29 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentuSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ezame', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prezensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('Presente', 'Presente'), ('Falta', 'Falta'), ('Lisensa', 'Lisensa'), ('Moras', 'Moras')], max_length=10)),
                ('alokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.alokasimateria')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prezensas', to='users.estudante')),
            ],
            options={
                'verbose_name': 'Prezensa',
                'verbose_name_plural': 'Prezensa Sira',
            },
        ),
        migrations.CreateModel(
            name='ValorFinalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('disiplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disiplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.estudante')),
            ],
        ),
    ]
