# Generated by Django 6.0.3 on 2026-05-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentuSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretor_naran', models.CharField(max_length=255)),
                ('diretor_gelar', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ezame', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
