# Generated by Django 6.0.3 on 2026-05-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_dokumentusetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentusetting',
            name='diretor_gelar',
        ),
        migrations.RemoveField(
            model_name='dokumentusetting',
            name='diretor_naran',
        ),
    ]
